/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      'surface': '#0e0e0e',
      'surface-container-lowest': '#000000',
      'surface-container-low': '#131313',
      'surface-container': '#1a1a1a',
      'surface-container-high': '#20201f',
      'surface-container-highest': '#262626',
      'surface-bright': '#2c2c2c',
      'surface-variant': '#484847',
      'primary': '#69daff',
      'primary-container': '#00cffc',
      'on-primary': '#000a0f',
      'on-primary-container': '#b3e9ff',
      'secondary': '#6bfe9c',
      'secondary-container': '#00522e',
      'on-secondary': '#000e08',
      'on-secondary-fixed': '#a6ffcf',
      'tertiary': '#ffe084',
      'tertiary-container': '#664d00',
      'on-tertiary': '#1f1600',
      'on-tertiary-fixed': '#ffebc2',
      'error': '#ff716c',
      'error-container': '#660e08',
      'on-error': '#ffffff',
      'on-error-container': '#ffb4ae',
      'outline-variant': '#484847',
      'on-surface': '#ffffff',
      'on-surface-variant': '#adaaaa',
      'on-surface-dim': '#ffffff',
      'white': '#ffffff',
      'black': '#000000',
      'transparent': 'transparent',
    },
    fontFamily: {
      'display': ['Manrope', 'sans-serif'],
      'body': ['Inter', 'sans-serif'],
      'sans': ['Inter', 'sans-serif'],
    },
    fontSize: {
      'display-lg': ['3.5rem', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
      'display-md': ['2.8rem', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
      'display-sm': ['2.2rem', { lineHeight: '1.1', fontWeight: '600', letterSpacing: '-0.02em' }],
      'headline-lg': ['2rem', { lineHeight: '1.2', fontWeight: '600' }],
      'headline-md': ['1.5rem', { lineHeight: '1.2', fontWeight: '600' }],
      'headline-sm': ['1.25rem', { lineHeight: '1.2', fontWeight: '600' }],
      'body-lg': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
      'body-md': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
      'body-sm': ['0.75rem', { lineHeight: '1.4', fontWeight: '400' }],
      'label-md': ['0.75rem', { lineHeight: '1.2', fontWeight: '500', letterSpacing: '0.05em' }],
      'label-sm': ['0.6875rem', { lineHeight: '1.2', fontWeight: '500', letterSpacing: '0.05em' }],
      'xs': ['0.75rem'],
      'sm': ['0.875rem'],
      'base': ['1rem'],
      'lg': ['1.125rem'],
      'xl': ['1.25rem'],
      '2xl': ['1.5rem'],
    },
    spacing: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
      '80': '20rem',
      '96': '24rem',
    },
    borderRadius: {
      'none': '0px',
      'sm': '0px',
      'md': '0px',
      'lg': '0px',
      'full': '0px',
      'DEFAULT': '0px',
    },
    animation: {
      'fadeIn': 'fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'slideUp': 'slideUp 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'glow': 'glow 0.3s ease-in-out',
    },
    keyframes: {
      fadeIn: {
        '0%': { opacity: '0' },
        '100%': { opacity: '1' },
      },
      slideUp: {
        '0%': { transform: 'translateY(16px)', opacity: '0' },
        '100%': { transform: 'translateY(0)', opacity: '1' },
      },
      glow: {
        '0%': { boxShadow: '0 0 0 rgba(164, 230, 255, 0)' },
        '100%': { boxShadow: '0 0 8px rgba(164, 230, 255, 0.3)' },
      },
    },
    boxShadow: {
      'ambient': '0 0 32px rgba(0, 0, 0, 0.4)',
    },
    backdropBlur: {
      'glass': '20px',
    },
  },
  plugins: [],
}
