/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      'surface':                    '#131313',
      'surface-dim':                '#131313',
      'surface-container-lowest':   '#0e0e0e',
      'surface-container-low':      '#1c1b1b',
      'surface-container':          '#201f1f',
      'surface-container-high':     '#2a2a2a',
      'surface-container-highest':  '#353534',
      'surface-bright':             '#3a3939',
      'surface-variant':            '#353534',
      'background':                 '#131313',
      'primary':                    '#a4e6ff',
      'primary-container':          '#00d1ff',
      'primary-fixed':              '#b7eaff',
      'primary-fixed-dim':          '#4cd6ff',
      'on-primary':                 '#003543',
      'on-primary-container':       '#00566a',
      'on-primary-fixed':           '#001f28',
      'on-primary-fixed-variant':   '#004e60',
      'inverse-primary':            '#00677f',
      'secondary':                  '#9ccee2',
      'secondary-container':        '#184f60',
      'secondary-fixed':            '#b8eafe',
      'secondary-fixed-dim':        '#9ccee2',
      'on-secondary':               '#003543',
      'on-secondary-container':     '#8ec0d3',
      'on-secondary-fixed':         '#001f28',
      'on-secondary-fixed-variant': '#154d5d',
      'tertiary':                   '#ffd59c',
      'tertiary-container':         '#feb127',
      'tertiary-fixed':             '#ffddb1',
      'tertiary-fixed-dim':         '#ffba49',
      'on-tertiary':                '#442b00',
      'on-tertiary-container':      '#6b4700',
      'on-tertiary-fixed':          '#291800',
      'on-tertiary-fixed-variant':  '#624000',
      'error':                      '#ffb4ab',
      'error-container':            '#93000a',
      'on-error':                   '#690005',
      'on-error-container':         '#ffdad6',
      'outline':                    '#859399',
      'outline-variant':            '#3c494e',
      'on-surface':                 '#e5e2e1',
      'on-surface-variant':         '#bbc9cf',
      'on-background':              '#e5e2e1',
      'inverse-surface':            '#e5e2e1',
      'inverse-on-surface':         '#313030',
      'surface-tint':               '#4cd6ff',
      'white':                      '#ffffff',
      'black':                      '#000000',
      'transparent':                'transparent',
    },
    fontFamily: {
      'display':  ['Manrope', 'sans-serif'],
      'headline': ['Manrope', 'sans-serif'],
      'body':     ['Manrope', 'sans-serif'],
      'label':    ['Manrope', 'sans-serif'],
      'sans':     ['Manrope', 'sans-serif'],
      'mono':     ['ui-monospace', 'monospace'],
    },
    fontSize: {
      'display-lg': ['3.5rem',   { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
      'display-md': ['2.8rem',   { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
      'display-sm': ['2.2rem',   { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
      'headline-lg':['2rem',     { lineHeight: '1.2', fontWeight: '700' }],
      'headline-md':['1.5rem',   { lineHeight: '1.2', fontWeight: '700' }],
      'headline-sm':['1.25rem',  { lineHeight: '1.2', fontWeight: '700' }],
      'body-lg':    ['1rem',     { lineHeight: '1.5', fontWeight: '400' }],
      'body-md':    ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
      'body-sm':    ['0.75rem',  { lineHeight: '1.4', fontWeight: '400' }],
      'label-md':   ['0.75rem',  { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.1em' }],
      'label-sm':   ['0.6875rem',{ lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.1em' }],
      'xs':  ['0.75rem'],
      'sm':  ['0.875rem'],
      'base':['1rem'],
      'lg':  ['1.125rem'],
      'xl':  ['1.25rem'],
      '2xl': ['1.5rem'],
    },
    spacing: {
      '0': '0', '0.5': '0.125rem', '1': '0.25rem', '1.5': '0.375rem',
      '2': '0.5rem', '2.5': '0.625rem', '3': '0.75rem', '3.5': '0.875rem',
      '4': '1rem', '5': '1.25rem', '6': '1.5rem', '7': '1.75rem',
      '8': '2rem', '9': '2.25rem', '10': '2.5rem', '11': '2.75rem',
      '12': '3rem', '14': '3.5rem', '16': '4rem', '20': '5rem',
      '24': '6rem', '28': '7rem', '32': '8rem', '36': '9rem',
      '40': '10rem', '44': '11rem', '48': '12rem', '52': '13rem',
      '56': '14rem', '60': '15rem', '64': '16rem', '72': '18rem',
      '80': '20rem', '96': '24rem',
    },
    borderRadius: {
      'none':    '0px',
      'sm':      '0px',
      'md':      '0px',
      'lg':      '0px',
      'xl':      '0px',
      'full':    '9999px',
      'DEFAULT': '0px',
    },
    animation: {
      'fadeIn':  'fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'slideUp': 'slideUp 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'shimmer': 'shimmer 0.7s ease forwards',
    },
    keyframes: {
      fadeIn:  { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
      slideUp: { '0%': { transform: 'translateY(16px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
      shimmer: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
    },
    boxShadow: {
      'ambient': '0 0 32px rgba(0, 209, 255, 0.06)',
    },
    backdropBlur: {
      'glass': '20px',
    },
  },
  plugins: [],
}
